---
- hosts: all
  become: true

  vars:
    gitlab_url: "http://gitlab.pipeline.ci"
    internal_server: true


  tasks:
  - name: Checking Ansible connectivity to Linux nodes
    ping:

  - name: Prepare Docker on Linux node
    include_tasks: prepare-docker-linux.yml
    tags: install_docker

  - name: Install Gitlab on Linux node
    include_tasks: install-gitlab.yml
    tags: install_gitlab

  - name: Prepare Let´s Encrypt for Gitlab - externally accessable server
    include_tasks: letsencrypt-externally-accessable-server.yml
    vars:
      letsencrypt_mailadress: "gitlab.pipeline@mail.com"
      gitlab_domain: "pipeline.ci"
    when: not internal_server
    tags: letsencrypt

  - name: Prepare Let´s Encrypt for Gitlab - externally accessable server
    include_tasks: letsencrypt-internal-server.yml
    vars:
      gitlab_domain: "gitlab.pipeline.jonashackt.io"
    when: internal_server
    tags: letsencrypt

  - name: Install & Configure Gitlab Runner for Docker
    include_tasks: gitlab-runner.yml
    tags: gitlab_runner
