---
- hosts: all
  become: true

  tasks:
  - name: Checking Ansible connectivity to Linux nodes
    ping:

  - name: Prepare Docker on Linux nodes
    include_tasks: prepare-docker-linux.yml host=linux

