---
- hosts: all
  become: true

  vars:
    gitlab_url: "http://gitlab.pipeline.ci"
    https_internal_server: false

  tasks:
  - name: Checking Ansible connectivity to Linux nodes
    ping:

  - name: Prepare Docker on Linux node
    include_tasks: prepare-docker-linux.yml
    tags: install_docker

  - name: Install Gitlab on Linux node
    include_tasks: install-gitlab.yml
    tags: install_gitlab

  - name: Prepare Let´s Encrypt certificates for Gitlab
    include_tasks: letsencrypt.yml
    vars:
      gitlab_domain: "gitlab.pipeline.jonashackt.io"
    when: https_internal_server
    tags: letsencrypt

  - name: Install & Configure Gitlab Runner for Docker
    include_tasks: gitlab-runner.yml
    tags: gitlab_runner
